# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: ff5c797cb4446a33355c19a60b42ce091fb8016fb6708fb2e34e1201ffe21cfe7e60411e51e1d7a6cdbd1d4a919e1127cd834539cb9e51fb9ef3e61da55f5183

test:
  secret_key_base: 18f7b3315bce292d2da571dd97f8b6b938c19dbcdd548df6245806421f248e84a1750d66c1c6fc3af9ba07dae369255174c5bcb715f438c31c9e29ab9e399d08

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
